In [86]:
import numpy as np
from astropy.io import fits
import matplotlib.pyplot as plt
%matplotlib tk

In [270]:
def centroid(fits_file):
    dt = fits.open('%s'%fits_file)[0].data
    dt[:,254:258]=np.median(dt) #fixing bad column of pixels, replacing them with median value of the image

    r = 20 # radius
    x_centroid = []
    y_centroid = []
    x_centroid_err = []
    y_centroid_err = []


    for i in range(20):
        peak_loc = np.where(dt==dt.max())
        star_img=dt[peak_loc[0][0]-r:peak_loc[0][0]+r,peak_loc[1][0]-r:peak_loc[1][0]+r]

        x_collapse=np.mean(star_img,axis=1) #collapsing the image along x-axis
        y_collapse=np.mean(star_img,axis=0) #collapsing the iamge along y-axis

        pos_x=np.arange(peak_loc[1][0]-r,peak_loc[1][0]+r)#x-position array to be used in centroid calculation
        pos_y=np.arange(peak_loc[0][0]-r,peak_loc[0][0]+r)#y-position array to be used in centroid calculation
        print(peak_loc[0][0],peak_loc[0])
        if x_collapse.shape[0] != star_img.shape[0] or y_collapse.shape[0] != star_img.shape[0]:
            continue
        y_centroid.append(np.sum(x_collapse*pos_y)/np.sum(x_collapse)) #computing the x-centroid
        x_centroid.append(np.sum(y_collapse*pos_x)/np.sum(y_collapse)) #computing the y-centroid

        x_centroid_err.append((np.sum(y_collapse*(pos_x-x_centroid[i])**2)/(np.sum(y_collapse))**2)**0.5) #errors on centroids
        y_centroid_err.append((np.sum(x_collapse*(pos_y-y_centroid[i])**2)/(np.sum(x_collapse))**2)**0.5)

        dt[peak_loc[0][0]-r:peak_loc[0][0]+r,peak_loc[1][0]-r:peak_loc[1][0]+r] = 0
    return np.array([[x_centroid,y_centroid],[x_centroid_err,y_centroid_err]])

In [249]:
dt = fits.open('%s'%dt_nam)[0].data
r = 50
peak_loc = np.where(dt==dt.max())
peak_loc

(array([844, 844, 844, 845, 845, 845, 845, 846, 846, 846, 846, 846, 847,
        847, 847, 847, 847, 848, 848]),
 array([491, 492, 493, 491, 492, 493, 494, 491, 492, 493, 494, 495, 491,
        492, 493, 494, 495, 492, 493]))

In [274]:
plt.imshow(np.log(dt),origin='lower',interpolation='nearest')
plt.scatter(stuff[0][0],stuff[0][1],color='red',marker='o',s=50,facecolor='none',edgecolor='r')
plt.show()

In [271]:
dt_nam = 'astroid_data/kalliope/df1/d1037.fits'
stuff = centroid(dt_nam)
stuff

845 [845 845 845 846 846 846 846 846 847 847 847 847 847 848 848 848 848 849
 849]
435 [435]
998 [998]
574 [574]
66 [66]
796 [796]
487 [487]
803 [803]
568 [568]
598 [598]
789 [789]
228 [228]
464 [464]
932 [932]
633 [633]
42 [42]
324 [324]
748 [748]
116 [116]
48 [48]


array([[[4.91610366e+02, 4.18702769e+02, 1.52522969e+02, 3.58497413e+02,
         4.26741807e+02, 1.02195050e+03, 9.65497644e+02, 5.53499484e+02,
         7.12497870e+02, 4.51499987e+02, 9.53510684e+02, 1.71500972e+02,
         1.82502017e+02, 5.47512183e+02, 9.10499021e+02, 6.76501436e+02,
         1.72516092e+02, 4.65490942e+02, 9.10502077e+02, 3.33503931e+02],
        [8.45891191e+02, 4.34709636e+02, 9.97537242e+02, 5.73466312e+02,
         6.54899467e+01, 7.95521084e+02, 4.86509893e+02, 8.02509502e+02,
         5.67501353e+02, 5.97499913e+02, 7.88491695e+02, 2.27513712e+02,
         4.63502370e+02, 9.31519179e+02, 6.32497077e+02, 4.15111898e+01,
         3.23507956e+02, 7.47488698e+02, 1.15500228e+02, 4.74950499e+01]],

       [[2.11676230e-02, 3.31670118e-02, 5.14281852e-02, 5.25711585e-02,
         5.32690483e-02, 5.35492832e-02, 5.35821537e-02, 5.39610676e-02,
         5.40438403e-02, 5.41128073e-02, 5.55892969e-02, 5.42729502e-02,
         5.55812282e-02, 5.41712322e-02, 5.4527

In [187]:
star_img=dt[peak_loc[0][1]-r:peak_loc[0][1]+r,peak_loc[1][1]-r:peak_loc[1][1]+r]
star_img

array([[1082, 1072, 1086, ..., 1084, 1084, 1090],
       [1057, 1083, 1091, ..., 1091, 1091, 1086],
       [1080, 1079, 1097, ..., 1076, 1101, 1077],
       ...,
       [1074, 1085, 1101, ..., 1075, 1098, 1065],
       [1078, 1072, 1088, ..., 1100, 1089, 1086],
       [1083, 1087, 1082, ..., 1062, 1082, 1088]], dtype=uint16)

In [188]:
x_collapse=np.mean(star_img,axis=0) #collapsing the image along x-axis
y_collapse=np.mean(star_img,axis=1) #collapsing the iamge along y-axis

x_collapse,y_collapse

(array([1081.09, 1082.03, 1083.09, 1082.34, 1083.29, 1084.39, 1083.83,
        1083.57, 1085.1 , 1085.08, 1086.28, 1085.29, 1087.16, 1087.78,
        1086.07, 1087.9 , 1087.67, 1089.33, 1090.3 , 1088.97, 1090.13,
        1092.4 , 1092.65, 1092.55, 1094.73, 1098.25, 1099.21, 1101.15,
        1103.89, 1107.86, 1109.71, 1113.71, 1118.14, 1124.24, 1128.46,
        1135.33, 1140.86, 1151.61, 1162.55, 1174.73, 1197.12, 1221.73,
        1263.95, 1328.95, 1441.01, 1660.25, 2093.63, 2950.17, 4485.89,
        5497.65, 6042.82, 6103.17, 5529.67, 4405.4 , 2780.99, 1914.07,
        1560.58, 1387.62, 1286.05, 1227.05, 1188.62, 1166.4 , 1150.61,
        1140.89, 1137.85, 1130.63, 1131.65, 1138.59, 1133.88, 1129.5 ,
        1120.29, 1114.61, 1107.6 , 1102.57, 1098.82, 1098.03, 1095.19,
        1092.75, 1093.2 , 1091.1 , 1089.46, 1090.52, 1087.41, 1088.94,
        1091.16, 1094.41, 1094.31, 1095.  , 1092.36, 1088.02, 1085.8 ,
        1084.71, 1082.92, 1082.03, 1083.72, 1081.91, 1082.97, 1082.06,
      

In [189]:
pos_x=np.arange(peak_loc[1].any()-r,peak_loc[1].any()+r)#x-position array to be used in centroid calculation
pos_y=np.arange(peak_loc[0].any()-r,peak_loc[0].any()+r)#y-position array to be used in centroid calculation
pos_x,pos_y

(array([-49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37,
        -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24,
        -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11,
        -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50]),
 array([-49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37,
        -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24,
        -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11,
        -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  

In [190]:
print(np.sum(x_collapse*pos_y)/np.sum(x_collapse))#computing the x-centroid)
print(np.sum(y_collapse*pos_x)/np.sum(y_collapse))#computing the y-centroid)
star_img.shape

0.7206765585767007
1.0015261258981805


(100, 100)